
services:

  mssql:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Admin@123'
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433 
    ports: 
      - "1455:1433"

  backend:
    build:
      context: .
      dockerfile: src/InvBG.Contacts.Backend/Dockerfile
    ports:
      - 5008:80
    environment:
        - ASPNETCORE_URLS=http://+:80
    depends_on:
      - mssql
  
  frontend:
    build:
        context: src/InvBG.Contacts.Frontend
    ports:
      - 4200:4200
    depends_on:
      - backend